image: maven:latest

variables:
  #  MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
  paths:
    - .m2/repository/
    - target/

Build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

Add:
  stage: test
  script:
    - mvn -Dtest=recursion.AddTest test

Collatz:
  stage: test
  script:
    - mvn -Dtest=recursion.CollatzTest test

Fact:
  stage: test
  script:
    - mvn -Dtest=recursion.FactTest test


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."