image: maven:3.5.0-jdk-8

cache:
  paths:
    - maven.repository/

variables:
  MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"


build-job:
  stage: build
  script:
    - mvn compile

Add:
  stage: test
  script:
    - mvn -Dtest=recursion.AddTest test

Collatz:
  stage: test
  script:
    - mvn -Dtest=recursion.CollatzTest test

Fact:
  stage: test
  script:
    - mvn -Dtest=recursion.FactTest test

All:
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    #    - target/failsafe-reports/TEST-*.xml


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."