image: maven:latest

cache:
  paths:
   # - maven.repository/
    - ./.m2/repository/


variables:
#  MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode"

build-job:
  stage: build
  script:
    - mvn compile

Add:
  stage: test
  script:
    - mvn -Dtest=recursion.AddTest test

Collatz:
  stage: test
  script:
    - mvn -Dtest=recursion.CollatzTest test

Fact:
  stage: test
  script:
    - mvn -Dtest=recursion.FactTest test

All:
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    #    - target/failsafe-reports/TEST-*.xml


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."