image: maven:latest

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - mvn compile

Add:
  stage: test
  script:
    - mvn -Dtest=recursion.AddTest test

Collatz:
  stage: test
  script:
    - mvn -Dtest=recursion.CollatzTest test

Fact:
  stage: test
  script:
    - mvn -Dtest=recursion.FactTest test

Report:
  stage: test
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."