name: Praktikum Workflow
on: [push]
jobs:

  fact:
    name: FactTest
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - run: mvn compile
      - run: mvn -Dtest=recursion.FactTest test

  binom:
    name: BinomTest
    needs: fact
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - run: mvn compile
      - run: mvn -Dtest=recursion.BinomTest test

  ggt:
    name: GgtTest
    needs: binom
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - run: mvn compile
      - run: mvn -Dtest=recursion.GgtTest test

  fib:
    name: FibTest
    needs: ggt
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - run: mvn compile
      - run: mvn -Dtest=recursion.FibTest test

